#!/bin/sh
DIR=dotfiles
cd `dirname $0`/$DIR
for i in `find . -type f`; do
	j="${i##./}"
	d=`dirname "$j"` 
	b=`basename "$j"`
        mkdir -p "$HOME/$d" 2> /dev/null
        ln -sf "$PWD/$j" "$HOME/$j"
done
cd "$OLDPWD"
